
<div id="page-title">

    <div class="row">

        <div class="ten columns centered text-center">
            <h2 style="font: 50px/60px raleway-bold, sans-serif;color: #fff;padding: 0;margin: 0 0 18px 0;text-shadow: 0px 1px 5px rgba(0, 0, 0, .3);letter-spacing:25px">书籍清单</h2>
            <h1 hidden>读书笔记</h1>
        </div>

    </div>

</div>

<section id="works">

    <div class="row">

        <div style="text-align:center" id="ads">
            <?php echo \Application\Model\Config::getValueByMark('ads1');?>
        </div>

        <div id="portfolio-wrapper" class="bgrid-quarters s-bgrid-halves">


        <?php
            if(!empty($bookDetails)){
                foreach ($bookDetails as $book){
        ?>
            <div class="columns portfolio-item" style="height: 500px">
                <div class="item-wrap">
                    <a href="/<?php echo $book['bookKey'] ?>">

                    <?php
                    if (empty($book['pic']) == false) {
                        ?>
                        <img alt="<?php echo $book['bookName'] ?>" src="<?php echo $book['pic'] ?>" style="height: 350px; width: 300px">
                        <?php
                    } else {
                        ?>
                        <img alt="<?php echo $book['bookName'] ?>" src="/images/management-platform/logo.png" style="height: 350px; width: 300px">
                        <?php
                    }
                    ?>

                        <div class="overlay"></div>
                        <div class="link-icon"><i class="fa fa-link"></i></div>
                    </a>
                    <div class="portfolio-item-meta">
                        <h5><a href="/<?php echo $book['bookKey'] ?>"><?php echo $book['bookName'] ?></a></h5>
                        <p>
                            <?php
                                if(!empty($book['bookSubname'])){
                                    echo $book['bookSubname'];
                                }
                            ?>
                        </p>
                    </div>
                </div>
            </div>

        <?php
                }
            }
        ?>

        </div>

    </div>


    <div style="text-align:center" id="ads">
        <?php echo \Application\Model\Config::getValueByMark('ads3');?>
    </div>

</section>