<!DOCTYPE html>
<html class="no-js ie ie7" lang="en">
<html class="no-js ie ie8" lang="en">
<html class="no-js" lang="en">
<head>

    <meta charset="utf-8">
    <title><?php
        if (empty($htmlTitle) == false) {
            echo $htmlTitle;
        }
        ?></title>
    <meta name="keywords"  content="<?php
    if (empty($htmlKeywords) == false) {
        echo $htmlKeywords;
    }
    ?>" />
    <meta name="description" content="<?php
    if (empty($htmlDescription) == false) {
        echo $htmlDescription;
    }
    ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="/css/default.css">
    <link rel="stylesheet" href="/css/layout.css">
    <link rel="stylesheet" href="/css/media-queries.css">
    <!-- 代码高亮 -->
    <link rel="stylesheet" href="/js/highlight/styles/default.css">
    <script src="/js/highlight/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <style>
        ins{
            background-color: transparent;
        }
    </style>


    <script src="/js/modernizr.js"></script>

    <link rel="shortcut icon" href="/images/favicon.ico">

</head>

<body>

<header>

    <div class="row">

        <div class="twelve columns">

            <div class="logo">
                <a href="/">
                    <img alt="读书笔记" src="/images/logo.png">
                </a>
            </div>

            <nav id="nav-wrap">

                <a class="mobile-btn" href="#nav-wrap" title="显示导航">显示导航</a>
                <a class="mobile-btn" href="#" title="隐藏导航">隐藏导航</a>

                <ul id="nav" class="nav">

                    <li class="current"><a href="/">Home</a></li>
                    <li><span><a href="javascript:void(0)">书籍清单</a></span>
                        <ul>
                            <?php
                            if(!empty($bookList)){
                                if (!empty($oBook)) {
                                    // 当前页书籍不为空，放首位

                                    echo  "<li><a href=\"/$oBook->bookKey\">" . $oBook->bookName . "</a></li>";

                                    foreach ($bookList as $book){
                                        if($book['bookName'] != $oBook->bookName) {
                                            ?>
                                            <li>
                                                <a href="/<?php echo $book['bookKey'] ?>"><?php echo $book['bookName'] ?></a>
                                            </li>
                                            <?php
                                        }
                                    }
                                } else {
                                    // 当前书籍为空，循环输出

                                    foreach ($bookList as $book){
                                        ?>
                                        <li>
                                            <a href="/<?php echo $book['bookKey'] ?>"><?php echo $book['bookName'] ?></a>
                                        </li>
                                        <?php
                                    }
                                }
                            }
                            ?>
                        </ul>
                    </li>

                    <?php
                    if($this->view->getControllerName() != 'index') {
                        ?>
                        <li><span><a href="javascript:void(0)">笔记类型</a></span>
                            <ul>
                                <li><a href="/<?php echo $oBook->bookKey; ?>/">全部</a></li>
                                <?php
                                if(!empty($typeList)){
                                    foreach ($typeList as $type){
                                        ?>
                                        <li><a href="/<?php echo $oBook->bookKey; ?>/<?php echo $type ?>"><?php echo $type ?></a></li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </li>
                        <?php
                    }
                    ?>

                </ul>

            </nav>

        </div>

    </div>

</header>

<?php echo $this->getContent(); ?>

<footer style="margin-top: 30px; margin-bottom: 30px;">

    <div class="row">

        <div class="twelve columns">

            <?php
            $links = str_replace('\\\\','\\',\Application\Model\Config::getValueByMark('links'));
            if (empty($links) == false) {
                ?>
                <p class="text-muted text-center small p-0 mb-4">
                    友情连接：<?php echo $links; ?>
                </p>
                <?php
            }
            ?>

            <p class="text-muted text-center small p-0 mb-4">
                <?php echo \Application\Model\Config::getValueByMark('copyright');?> |
                <?php echo str_replace('\\\\','\\',\Application\Model\Config::getValueByMark('statistics'));?>
            </p>

        </div>

        <div id="go-top" style="display: block;"><a title="返回顶部" href="#">返回顶部</a></div>

    </div>

</footer>

<script src="/js/jquery/jquery-3.1.1.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery/jquery-3.2.1.min.js"><\/script>')</script>
<script type="text/javascript" src="/js/jquery/jquery-migrate-1.2.1.min.js"></script>

<script src="/js/jquery/jquery.flexslider.js"></script>
<script src="/js/doubletaptogo.js"></script>
<script src="/js/init.js"></script>


</body>
</html>