
<div id="page-title" style="padding-top: 0px; padding-bottom: 0px;">

    <div class="row">

        <div id="portfolio-wrapper" class="bgrid-quarters s-bgrid-halves">
            <div class="columns portfolio-item" style="width: 25%">
                <?php
                if (empty($oBook->pic) == false) {
                    ?>
                    <img src="<?php echo $oBook->pic; ?>" alt="Shard" class="shard">
                    <?php
                }
                ?>
            </div>
        </div>

        <div class="ten columns centered">
            <div style="padding-top: 20px"></div>
            <h2 style="color: white; padding-bottom: 30px">《<?php echo $oBook->bookName; ?>》笔记
                <?php
                    if (empty($infoType) == false) {
                        echo '—' . $infoType;
                    }
                ?>
            </h2>

            <?php
            if (empty($oBook->bookSubname) == false) {
                ?>
                <h4 style="color: white; padding-bottom: 30px"><?php echo $oBook->bookSubname; ?></h4>
                <?php
            }

            if (empty($oBook->author) == false) {
                ?>
                <h4 style="color: white">作者：<?php echo $oBook->author; ?></h4>
                <?php
            }
            ?>

        </div>

    </div>

</div>

<div class="content-outer">

    <div id="page-content" class="row">

        <div style="text-align:center" id="ads">
            <?php echo \Application\Model\Config::getValueByMark('ads1');?>
        </div>

        <div id="primary" class="eight columns">

        <?php
            if (!empty($infoList)) {
                foreach ($infoList as $row) {
        ?>

            <article class="post">

                <div class="entry-header cf">

                    <!-- 知识点 -->
                    <h1><a href="/book/info/<?php echo $row['infoId'] ?>"><?php echo $row['title'] ?></a></h1>

                    <!-- 类型 -->
                    <h5 class="widget-title"><?php echo $row['type'] ?></h5>

                </div>

                <!-- 大图 -->
                <div class="post-thumb">

                <?php
                    if(!empty($row['pic'])){
                ?>
                        <a href="/book/info/<?php echo $row['infoId'] ?>">
                            <img src="<?php echo $row['pic']; ?>" alt="post-image" title="post-image" width="300px">
                        </a>
                <?php
                    }
                ?>

                </div>

                <!-- 内容 -->
                <div class="post-content">

                    <p>
                        <?php
                            $introduce = htmlspecialchars_decode($row['introduce'], ENT_QUOTES);

                            $lineArray = explode("</p>",$introduce);

                            if(count($lineArray) > 3){
                                for ($i = 0; $i < 3; $i++){
                                    echo $lineArray[$i];
                                }
                                echo '<p>......</p>';
                            } else {
                                echo $introduce;
                            }
                        ?>
                    </p>

                </div>

                <hr>

            </article>
                <?php
                }
            }
            ?>


            <div style="text-align:center" id="ads">
                <?php echo \Application\Model\Config::getValueByMark('ads2');?>
            </div>


            <div id="comments">

            <?php
                if (!empty($commentList)) {
            ?>
                <h3><?php echo count($commentList); ?> 条评论</h3>


                <ol class="commentlist" style="margin-left: 20px">

                    <?php
                        foreach ($commentList as $row) {
                            ?>

                            <li class="depth-1">

                                <div class="comment-info">
                                    <cite><?php echo $row['realname']; ?></cite>

                                    <div class="comment-meta">
                                        <time class="comment-time"><?php echo substr($row['createTime'], 2,8); ?></time>
                                    </div>
                                </div>

                                <div class="comment-text">
                                    <p><?php echo $row['content']; ?></p>
                                </div>

                            </li>
                            <?php
                        }
                    ?>

                </ol>

                <?php
                    }
                ?>


                <div class="respond">

                    <h1 style="text-align: center; letter-spacing:25px">评论</h1>


                    <form name="contactForm" id="contactForm" method="post" style="margin-top: 0px">
                        <fieldset>

                            <div class="cf" style="float: left">
                                <label for="commentRealname" style="letter-spacing:15px; float: left; padding-left: 10px">昵称<span class="required">*</span></label>
                                <br>
                                <input name="commentRealname" type="text" id="commentRealname" placeholder="请输入您的昵称"/>
                            </div>

                            <div class="cf" style="float: left; padding-left: 120px">
                                <label for="commentEmail" style="letter-spacing:2px; float: left; padding-left: 10px">Email<span class="required" style="padding-left: 15px">*</span></label>
                                <br>
                                <input name="commentEmail" type="text" id="commentEmail" placeholder="请输入您的Email"/>
                            </div>

                            <div class="cf" style="clear: both">
                                <label for="commentContent" style="letter-spacing:8px; float: left; padding-left: 10px">评论内容<span class="required">*</span></label>
                                <textarea name="commentContent" id="commentContent" rows="10" cols="50" placeholder="请输入评论内容..." style="resize: vertical;"></textarea>
                            </div>

                            <button type="submit" class="submit" style="display:block;margin:0 auto" onclick="submitComment()">提交评论</button>

                        </fieldset>
                    </form>

                </div>

            </div>

        </div>

        <div id="secondary" class="four columns end">

            <aside id="sidebar">

                <!-- 暂不启用 -->
                <!--<div class="widget widget_search">
                    <h5>查询</h5>
                    <form action="#">

                        <input class="text-search" type="text" placeholder="在这里查询...">
                        <input type="submit" class="submit-search" value="">

                    </form>
                </div>-->

                <div class="widget widget_categories">
                    <h5 class="widget-title">类型</h5>
                    <div class="tagcloud cf">
                        <a href="/<?php echo $oBook->bookKey; ?>/"><span style="font-size: 15px">全部</span></a>
                        <?php
                        if(!empty($typeList)){
                            foreach ($typeList as $type){
                                ?>
                                <a href="/<?php echo $oBook->bookKey; ?>/<?php echo $type ?>"><span style="font-size: 15px"><?php echo $type ?></span></a>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>

                <div style="text-align:center" id="ads">
                    <?php echo \Application\Model\Config::getValueByMark('ads4');?>
                </div>

                <div class="widget widget_categories" style="margin-top: 20px">
                    <h5 class="widget-title">其他书籍</h5>
                    <ul class="link-list cf">
                        <?php
                        if(!empty($bookList)){
                            if (!empty($oBook)) {
                                // 当前页书籍不为空，放首位

                                echo  "<li><a href=\"/$oBook->bookKey\">" . $oBook->bookName . "</a></li>";

                                foreach ($bookList as $book){
                                    if($book['bookName'] != $oBook->bookName) {
                                        ?>
                                        <li>
                                            <a href="/<?php echo $book['bookKey'] ?>"><?php echo $book['bookName'] ?></a>
                                        </li>
                                        <?php
                                    }
                                }
                            } else {
                                // 当前书籍为空，循环输出

                                foreach ($bookList as $book){
                                    ?>
                                    <li>
                                        <a href="/<?php echo $book['bookKey'] ?>"><?php echo $book['bookName'] ?></a>
                                    </li>
                                    <?php
                                }
                            }
                        }
                        ?>
                    </ul>
                </div>

            </aside>

        </div>

    </div>

    <div style="text-align:center" id="ads">
        <?php echo \Application\Model\Config::getValueByMark('ads3');?>
    </div>

</div>


<script>
    function submitComment() {
        commentRealname = $('#commentRealname').val();
        commentEmail = $('#commentEmail').val();
        commentContent = $('#commentContent').val();

        if (commentRealname.length > 20) {
            alert("昵称太长，不要超过20字！");
            return;
        }
        if (commentEmail.length > 500) {
            alert("Email太长，不要超过50字！");
            return;
        }
        if (commentContent == '') {
            alert("请输入评论内容！");
            return;
        }
        if (commentContent.length > 5000) {
            alert("评论内容太长，不要超过5000字！");
            return;
        }


        submitData = {
            bookId: <?php echo $oBook->bookId; ?>,
            commentRealname: commentRealname,
            commentEmail: commentEmail,
            commentContent: commentContent
        };

        $.post("/comment/submit", submitData, function(data) {
            if (data == 'true') {
                alert('评论已提交！');
                $("#commentRealname").val('');
                $("#commentEmail").val('');
                $("#commentContent").val('');
            } else {
                alert('评论提交失败！');
            }
        });

    }
</script>