<div style="position:relative;" id="contentFrame" style="height:100%">
    <div style="position:absolute;top:0;left:0;width:230px; height:100%">
        <ul class="easyui-datalist" title="书籍" lines="true" style="width:230px;" data-options="
	                idField: 'id',
                    height:windowHeight - 168,
	                onClickRow: showInfo
	            ">
            <?php
                if ($BookList['countAll'] > 0) {
                    foreach ($BookList['rowset'] as $row) {
                        ?>
            <li value="<?php echo $row['bookId']; ?>"><?php echo $row['bookName']; ?></li>

                        <?php
                    }
                }

            ?>
        </ul>

    </div>
    <div style="position:absolute;top:0;left:235px;height:100%;width:100%">
        <table id="dg" class="easyui-datagrid" title="知识点列表"
               toolbar="#toolbar" pagination="true"
               rownumbers="false" fitColumns="true" singleSelect="true">
            <thead>
            <tr>
                <th data-options="field:'infoId',width:50,align:'center'">编号</th>
                <th data-options="field:'type',width:100">类型</th>
                <th data-options="field:'title',width:300">知识点名称</th>
                <th data-options="field:'introduce',width:300">描述</th>
                <th data-options="field:'url',width:300">连接</th>
                <th data-options="field:'createTime',width:130,align:'center'">创建时间</th>
            </tr>
            </thead>
        </table>
        <script>
            $("#dg").css("height",(windowHeight - 168) + "px");
            $("#dg").css("width",(parseInt($("#contentFrame").css("width")) - 437) + "px");
        </script>
        <div id="toolbar">
            <?php
            if(\Application\Model\Admin::verifyAction($this, 'insert')) {
                ?>
                <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="newContent()">添加知识点</a>
                <?php
            }

            if(\Application\Model\Admin::verifyAction($this, 'update')) {
                ?>
                <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="editContent()">修改知识点</a>
                <?php
            }

            if(\Application\Model\Admin::verifyAction($this, 'delete')) {
                ?>
                <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="destroyContent()">删除知识点</a>
                <?php
            }
            ?>

            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            类型：<input id="ectype" class="easyui-combobox" name="ectype" style="width:150px" data-options="
                    valueField: 'id',
                    textField: 'text',
                    editable:false,
                    panelHeight:'auto'
                    ">
            &nbsp;&nbsp;
            名称：<input class="easyui-textbox" style="width:110px" id="keyword">
            <a href="#" class="easyui-linkbutton" iconCls="icon-search" onclick="findSubmit();">查询</a>
        </div>
    </div>
    <div id="dlg" class="easyui-window" style="padding:10px 20px;width:1050px;height:500px" closed="true" buttons="#dlg-buttons" resizable="true" data-options="modal:true,closed:true,iconCls:'icon-save',minimizable: false, collapsible:false">
        <div class="ftitle">知识点信息</div>
        <form id="fm" method="post" novalidate>
            <input name="bookId" type="hidden" id="bookId">

            <div style="margin-bottom:10px">
                <input class="easyui-textbox" name="type" style="width:95%" data-options="label:'类型:',required:true,validType:'length[1,10]'">
            </div>
            <div style="margin-bottom:10px">
                <input class="easyui-textbox" name="title" style="width:95%" data-options="label:'知识点名称:',required:true,validType:'length[2,255]'">
            </div>
            <div style="margin-bottom:10px">
                <input class="easyui-textbox" name="introduce" style="width:95%;height:200px" data-options="label:'描述:',validType:'length[0,1800]',multiline:true">
            </div>
            <div style="margin-bottom:10px">
                <input class="easyui-textbox" name="url" style="width:95%" data-options="label:'链接:',validType:'url'">
            </div>
        </form>
        <div style="text-align:center;padding:5px">
            <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-ok" onclick="saveContent()">保存</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:$('#dlg').dialog('close')">取消</a>
        </div>
    </div>

    <script type="text/javascript">
        var url;
        var bookId = 0;
        var BookName = 0;

        function findSubmit(){
            //alert($('#ectype').val());
            //alert($('#keyword').val());

            nowUrl = '/<?php echo $this->router->getModuleName(); ?>/info/list/' + bookId;
            nowWhere = '';
            if ($('#ectype').val() != '') {
                nowWhere = '?type=' + $('#ectype').val();
            }
            if ($('#keyword').val() != '') {
                if (nowWhere == '') {
                    nowWhere = '?';
                } else {
                    nowWhere += '&';
                }
                nowWhere += 'keyword=' + $('#keyword').val();
            }
            $('#dg').datagrid({
                url: nowUrl + nowWhere
            });
        }

        function showInfo(index, row){
            bookId = row.value;
            BookName = row.text;

            $('#dg').datagrid({
                url:'/<?php echo $this->router->getModuleName(); ?>/info/list/' + bookId
            });
            $('#ectype').combobox('setValue', '');
            $('#ectype').combobox('reload', '/<?php echo $this->router->getModuleName(); ?>/info/getBookType/' + bookId);
        }


        function newContent(){
            if(bookId == 0) {
                $.messager.show({
                    title: '提示',
                    msg: '请先选择书籍'
                });
                return;
            }
            $('#dlg').dialog('open').dialog('setTitle','添加知识点');
            $('#fm').form('clear');
            url = '/<?php echo $this->router->getModuleName(); ?>/info/insert';

        }
        function editContent(){
            var row = $('#dg').datagrid('getSelected');
            if (row){
                $('#dlg').dialog('open').dialog('setTitle','修改知识点');
                $('#fm').form('clear');
                $('#fm').form('load',row);

                url = '/<?php echo $this->router->getModuleName(); ?>/info/update/'+row.infoId;

            }
        }
        function saveContent(){
            $('#bookId').val(bookId);
            $('#fm').form('submit',{
                url: url,
                onSubmit: function(){
                    return $(this).form('validate');
                },
                success: function(result){
                    result = eval('('+result+')');
                    if (result.errorCode > 0){
                        showError(result);
                    } else {
                        $('#dlg').dialog('close');
                        $('#dg').datagrid('reload');
                    }
                }
            });
        }

        function destroyContent(){
            var row = $('#dg').datagrid('getSelected');
            if (row){
                $.messager.confirm('删除确认','您真的要删除此知识点?',function(r){
                    if (r){
                        $.post('/<?php echo $this->router->getModuleName(); ?>/info/delete',{id:row.infoId},function(result){
                            if (result.errorCode > 0){
                                showError(result);
                            } else {
                                $('#dg').datagrid('reload');
                            }
                        },'json');
                    }
                });

            }
        }

    </script>
    <style type="text/css">
        #fm{
            margin:0;
            padding:10px 10px;
        }
        .ftitle{
            font-size:14px;
            font-weight:bold;
            padding:5px 0;
            margin-bottom:10px;
            border-bottom:1px solid #ccc;
        }
        .fitem{
            margin-bottom:5px;
        }
        .fitem label{
            display:inline-block;
            width:45px;
        }
    </style>
<div>