<table id="dg" class="easyui-datagrid" style="width:100%; height: 100%;">
</table>
<script>
    $('#dg').datagrid({
        url:'/<?php echo $this->router->getModuleName(); ?>/book/list',
        toolbar:"#toolbar",
        pagination:"true",
        rownumbers: false,
        fitColumns:"true",
        singleSelect:"true",
        pageSize:"20",
        columns:[[
            {field:'bookId',title:'编号',width:20,align:'center'},
            {field:'bookName',title:'标题',width:100},
            {field:'bookSubname',title:'副名',width:100},
            {field:'bookKey',title:'标识',width:50},
            {field:'createTime',title:'创建时间',width:50,align:'center'},
        ]]
    });
</script>
<div id="toolbar">
    <?php
    if(\Application\Model\Admin::verifyAction($this, 'insert')) {
        ?>
        <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="newInfo()">添加</a>
        <?php
    }

    if(\Application\Model\Admin::verifyAction($this, 'update')) {
        ?>
        <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="editInfo()">编辑</a>
        <?php
    }

    if(\Application\Model\Admin::verifyAction($this, 'delete')) {
        ?>
        <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="delInfo()">删除</a>
        <?php
    }
    ?>
</div>

<div id="dlg" class="easyui-dialog" style="width:650px;height:370px;padding:10px 20px" closed="true" buttons="#dlg-buttons" data-options="modal:true">
    <div class="ftitle">书籍信息</div>
    <form id="fm" method="post" novalidate enctype="multipart/form-data">
        <div style="margin-bottom:10px">
            <input class="easyui-textbox" name="bookName" style="width:95%" data-options="label:'书名:',required:true,validType:'length[2,100]'">
        </div>
        <div style="margin-bottom:10px">
            <input class="easyui-textbox" name="bookSubname" style="width:95%" data-options="label:'副名:',validType:'length[0,100]'">
        </div>
        <div style="margin-bottom:10px">
            <input class="easyui-textbox" name="bookKey" style="width:95%" data-options="label:'标识:',required:true,validType:'length[2,40]'">
        </div>
        <div style="margin-bottom:10px">
            <input class="easyui-textbox" name="author" style="width:95%" data-options="label:'作者:',validType:'length[0,100]'">
        </div>
        <div style="margin-bottom:10px">
            <input class="easyui-filebox" name="picFile" data-options="label:'图片:',prompt:'选择文件...',buttonText:'选择书籍图片',accept:'image/gif,image/jpeg,image/jpg,image/png'" style="width:90%">
            <a href="#" id="picImg" class="easyui-linkbutton" onclick="window.open($('#picImg').attr('url'));"  data-options="iconCls:'icon-large-picture',size:'small',iconAlign:'top',disabled:true"></a>
        </div>
        <div style="margin-bottom:10px">
            <input class="easyui-textbox" name="readUrl" style="width:95%" data-options="label:'在线阅读URL:',validType:'url'">
        </div>
    </form>
</div>

<div id="dlg-buttons">
    <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-ok" onclick="saveInfo()">保存</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:$('#dlg').dialog('close')">关闭</a>
</div>
<script type="text/javascript">
    var url;
    function newInfo(){
        $('#dlg').dialog('open').dialog('setTitle','添加书籍');
        $('#fm').form('clear');
        $('#picImg').attr('url',"");
        $('#picImg').linkbutton('disable');
        url = '/<?php echo $this->router->getModuleName(); ?>/book/insert';
    }
    function editInfo(){
        var row = $('#dg').datagrid('getSelected');
        if (row){
            $('#dlg').dialog('open').dialog('setTitle','编辑书籍');
            $('#fm').form('load',row);

            $('#picImg').attr('url',"");
            $('#picImg').linkbutton('disable');

            if (row.pic != "") {
                $('#picImg').attr('url',row.pic);
                $('#picImg').linkbutton('enable');
            }


            url = '/<?php echo $this->router->getModuleName(); ?>/book/update/' + row.bookId;
        } else {
            $.messager.show({
                title: '警告',
                msg: '请选择要操作的书籍！',
                timeout: 2000,
                showType: 'slide'
            });
        }
    }
    function saveInfo(){
        $('#fm').form('submit',{
            url: url,
            onSubmit: function(){
                return $(this).form('validate');
            },
            success: function(result){
                var result = eval('('+result+')');
                if (result.errorCode > 0){
                    showError(result);
                } else {
                    $('#dlg').dialog('close');      // close the dialog
                    $('#dg').datagrid('reload');    // reload the user data
                }
            }
        });
    }
    function delInfo(){
        var row = $('#dg').datagrid('getSelected');
        if (row){
            $.messager.confirm('删除确认','您真的要删除此信息?',function(r){
                if (r){
                    $.post('/<?php echo $this->router->getModuleName(); ?>/book/delete/',{id:row.bookId},function(result){
                        if (result.errorCode > 0){
                            showError(result);
                        } else {
                            $('#dg').datagrid('reload');
                        }
                    },'json');
                }
            });
        } else {
            $.messager.show({
                title: '警告',
                msg: '请选择要操作的书籍！',
                timeout: 2000,
                showType: 'slide'
            });
        }
    }
</script>
<style type="text/css">
    #fm{
        margin:0;
        padding:10px 30px;
    }
    .ftitle{
        font-size:14px;
        font-weight:bold;
        padding:5px 0;
        margin-bottom:10px;
        border-bottom:1px solid #ccc;
    }
    .fitem{
        margin-bottom:5px;
    }
    .fitem label{
        display:inline-block;
        width:80px;
    }
</style>